spring:
  application:
    name: appointment-service
  #----DataBase settings----
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/ms_clinic_service_db

    #----JPA Settings----
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

#----FlyWay Settings---
#disaabled
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: ms_record_sc